# Generated by Django 3.2.8 on 2022-01-08 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('category', models.CharField(blank=True, max_length=50, primary_key=True, serialize=False, verbose_name='Category')),
            ],
        ),
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('description', models.CharField(blank=True, max_length=1000, verbose_name='Description')),
                ('postContent', models.CharField(blank=True, max_length=10000, verbose_name='Content')),
                ('category', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='portfolio.category')),
            ],
        ),
        migrations.CreateModel(
            name='postImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageName', models.CharField(blank=True, max_length=50)),
                ('image', models.ImageField(upload_to='photos', verbose_name='Image')),
                ('myPost', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='portfolio.post')),
            ],
        ),
    ]
